name: Java-mvn-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      artifact_path: ${{ steps.upload_artifact.outputs.artifact_path }}
      
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Set Build Label
      id: get-label
      run: echo "BUILD_LABEL=build-${{ github.run_number }}" >> $GITHUB_ENV
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Rename WAR file with Build Label
      run: mv target/*.war target/my-webapp-${{ env.BUILD_LABEL }}.war
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-webapp-${{ env.BUILD_LABEL }}
        path: target/my-webapp-${{ env.BUILD_LABEL }}.war
