name: Deploy-Java-WebApp

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get the latest artifact name dynamically
      id: get-artifact
      run: |
        ARTIFACT_NAME=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts" \
          | jq -r '.artifacts | sort_by(.created_at) | last | .name')
          
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
        echo "Found artifact: $ARTIFACT_NAME"

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: target/

    - name: List files in target directory (Debugging)
      run: ls -lah target/

    - name: Set WAR filename dynamically
      run: |
        WAR_FILE=$(ls target/*.war | head -n 1)
        echo "WAR_FILE=$WAR_FILE" >> $GITHUB_ENV

    - name: Install and Start Tomcat
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
        tar -xzf apache-tomcat-9.0.54.tar.gz
        sudo mv apache-tomcat-9.0.54 /opt/tomcat
        /opt/tomcat/bin/startup.sh

    - name: Deploy to Server
      env:
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      run: |
        echo "Deploying: $WAR_FILE"
        scp "$WAR_FILE" $DEPLOY_USER@$DEPLOY_SERVER:/opt/tomcat/webapps/
